# -*- coding: utf-8 -*-
"""PRODIGY_DS_01

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pRK6Yxe9XO29xaLGaHvLiyXtdkCduQd7
"""

import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
import pandas as pd

path = '/content/archive.zip'
data = pd.read_csv(path)
data.head()

data.columns

plt.figure(figsize=(4,4 ))
sns.histplot(data['Age Range'],kde=True, bins=10, color='red')
plt.title('Age Distribution')
plt.xlabel('Age')
plt.ylabel('Frequency')
plt.show()

# Create a bar chart for the gender distribution
plt.figure(figsize=(4, 3))
sns.countplot(x='Gender', data=data, palette='pastel')
plt.title('Distribution of Gender')
plt.xlabel('Gender')
plt.ylabel('Count')
plt.show()